### ISSUE TITLE
Error when using navigator and stacked series

### ISSUE THREAD

**Issue by veloek** [whawker/react-jsx-highcharts#299]
#### Bug or Feature Request?
Bug. "Cannot read property 'base' of undefined"

#### Description
Using a navigator with two stacked column series throws an error. It looks like it got introduced with highcharts version 8.1.1 as it works if you revert to 8.1.0.

The bug probably belongs with highcharts, but I didn't manage to reproduce it with vanilla highcharts so I reported it here.

#### How to reproduce
Run the demo.

#### Live demo demonstrating bug
https://stackblitz.com/edit/stockchart-updatepoints-false-qf2hes

#### Versions
* React JSX Highcharts version: 4.1.0
* Highcharts version: 8.1.1
* React version: 16.13.1

**Comment by veloek** [comment]
Here's another example showing an issue that seems to have come with highcharts 8.1.1:
https://stackblitz.com/edit/stockchart-updatepoints-false-1yudy4

For some reason only the series on the first y-axis is rendered. If you revert to highcharts 8.1.0 you can see that it works and both series are there.

Any idea what could've caused these issues, @whawker, @anajavi? Reading the changelog, 8.1.1 seems like a harmless upgrade...

**Comment by anajavi** [comment]
> Here's another example showing an issue that seems to have come with highcharts 8.1.1:
> https://stackblitz.com/edit/stockchart-updatepoints-false-1yudy4

Here's the same problem with vanilla highcharts: https://jsfiddle.net/2mb6vyrn/

The highcharts > 8.1.0 doesn't accept chart.setSize(undefined, undefined) anymore. It is called on this row:
https://github.com/whawker/react-jsx-highcharts/blob/f4d3acbb7e5e3ae2d094149b9ce8febcb706a8df/packages/react-jsx-highcharts/src/components/Chart/Chart.js#L32


Removing ```<Chart />``` from your examples gets rid of the call.

I think this should be fixed in react-jsx-highcharts.

**Comment by whawker** [comment]
Great spot @anajavi! I guess this is also related? https://github.com/highcharts/highcharts/issues/13752

**Comment by veloek** [comment]
I did a bisect of highcharts between 8.1.0 and 8.1.1 and found this to be the first bad commit: https://github.com/highcharts/highcharts/commit/57ce06ee444abb7b9c5e962c68dc6f5f831b64ae

**Comment by whawker** [comment]
Looks like that was modified again, in this commit https://github.com/highcharts/highcharts/pull/13717/commits/091c75e40fe198774d6517d86d1a39147643fe99 (still broken in 8.1.2 though)

**Comment by anajavi** [comment]
> Looks like that was modified again, in this commit [highcharts/highcharts@091c75e](https://github.com/highcharts/highcharts/commit/091c75e40fe198774d6517d86d1a39147643fe99) (still broken in 8.1.2 though)

I made reproduction for that too: https://github.com/highcharts/highcharts/issues/13680#issuecomment-643950051

**Comment by anajavi** [comment]
I created a issue in highcharts: https://github.com/highcharts/highcharts/issues/13995

@whawker do you think we should remove calls to setSize when width and height are undefined?

**Comment by whawker** [comment]
Thanks @anajavi. Yes I think we should avoid calling if both arguments are undefined.

As an aside, looks like we could also pull this out, and put it in a dedicated effect?
https://github.com/whawker/react-jsx-highcharts/blob/48928ef87f36703e8a0678bd1ee8c8dda48f2eed/packages/react-jsx-highcharts/src/components/Chart/Chart.js#L16-L19

```jsx
useEffect(() => {
  if (width || height) {
    chart.setSize(width, height)
  }
}, [width, height])
```

**Comment by whawker** [comment]
Published.

* `react-jsx-highcharts@4.1.1`
* `react-jsx-highstock@4.1.2`
* `react-jsx-highmaps@2.1.2`

**Comment by whawker** [comment]
Cheers for all the work in both identifying the issue and creating a workaround!

**Comment by anajavi** [comment]
Thanks for the quick release!

**Comment by whawker** [comment]
Realised I should keep this open, for visibility, until the upstream Highcharts bug is fixed

**Comment by anajavi** [comment]
Fix for this is released in highcharts@9.0.0.

We should allow that version as peerDependency: #325.
